---
- name: installing and launching filebeat
  hosts: webservers
  become: true
  tasks:

  # Download filebeat deb
  - name: download filebeat deb
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.4.0-amd64.deb

  # Install filebeat
  - name: install filebeat deb
    command: dpkg -i filebeat-7.4.0-amd64.deb

  # Copy filebeat configuration file to the VMs
  - name: drop in filebeat.yml
    copy:
      src: /etc/ansible/roles/files/filebeat-config.yml
      dest: /etc/filebeat/filebeat.yml

  # enable filebeat system module
  - name: enable and configure system module
    command: filebeat modules enable system

  # setup filebeat
  - name: setup filebeat
    command: filebeat setup

  # Start filebeat service
  - name: start filebeat service
    command: service filebeat start

  # Enable filebeat on boot
  - name: enable service filebeat on boot
    systemd:
       name: filebeat
       enabled: yes


